src/GmphanMvc/Areas/Visitor/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Gmphan.BusinessAccessLib;
using Gmphan.ModelLib;
using Gmphan.ModelLib.ViewModels;
using Markdig;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GmphanMvc.Areas.Visitor.Controllers
{
    [Area("Visitor")]
    public class PostController : Controller
    {
        private readonly ILogger<PostController> _logger;
        private readonly IPostServ _postServ;

        public PostController(ILogger<PostController> logger
                            , IPostServ postServ)
        {
            _logger = logger;
            _postServ = postServ;
        }

        public async Task<IActionResult> Index()
        {
            PostMetaView postMetaView = await _postServ.GetPostMetaViewServAsync();
            return View(postMetaView);
        }

        public async Task<IActionResult> GetPostDetail(int id)
        {
            PostDetailView postDetailView = await _postServ.GetPostDetailViewServAsync(id);
            return PartialView("_Detail", postDetailView);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Post obj)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _postServ.AddNewPostServAsync(obj);
            return RedirectToAction("index");
        }

        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0 || id == null)
            {
                return NotFound();
            }
            Post post = await _postServ.GetPostServAsync(id);
            return View(post);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Post obj)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _postServ.UpdatePostServAsync(obj);
            return RedirectToAction("index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

src/GmphanMvc/Areas/Visitor/Controllers/ProjectController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Gmphan.BusinessAccessLib;
using Gmphan.ModelLib;
using Gmphan.ModelLib.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace GmphanMvc.Areas.Visitor.Controllers
{
    [Area("Visitor")]
    public class ProjectController : Controller
    {
        private readonly ILogger<ProjectController> _logger;
        private readonly IProjectServ _projectServ;

        public ProjectController(ILogger<ProjectController> logger
                            , IProjectServ projectServ)
        {
            _logger = logger;
            _projectServ = projectServ;
        }

        public async Task<IActionResult> Index()
        {
            ProjectListView projectListView = await _projectServ.GetProjectListViewServAsync();
            return View(projectListView);
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Project obj)
        {
            if (ModelState.IsValid)
            {
                await _projectServ.AddNewProjectServAsync(obj);
                return RedirectToAction("Index");
            }
            // add tempdata for unsuccessfull adding
            return View(obj);
        }

        public async Task<IActionResult> Detail(int id)
        {
            ProjectDetailView projectDetailView = await _projectServ.GetProjectDetailViewServAsync(id);
            return View(projectDetailView);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Detail (ProjectDetailView obj)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }
            bool result = await _projectServ.UpdateProjectServAsync(obj);
            if(result) 
            {
                //need to include successful tempdata  
                return RedirectToAction("Detail", new { id = obj.Id }); 
            }  

            // if result is false
            return View(obj); //later need to add error tempdata here          
        }

        public async Task<IActionResult> Task(int id)
        {
            ProjectTaskView projectTaskView = await _projectServ.GetProjectTaskViewServAsync(id);
            return View(projectTaskView);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> TaskUpdate(ProjectTaskView obj)
        {
            if (!ModelState.IsValid) // add tempdata
            { 
                // Log or inspect ModelState errors for debugging
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                return BadRequest(ModelState); 
            }
            bool result = await _projectServ.UpdateTaskSerAsync(obj);
            if (result)
            {
                //add tempdata later    
                return RedirectToAction("Task", new { Id = obj.Id});
            }
            return BadRequest();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> _TaskCreate(ProjectTask obj)
        {
            if (ModelState.IsValid)
            {
                bool result = await _projectServ.AddNewTaskSerAsync(obj);
                if (result) 
                {
                    // add tempdata later
                    return RedirectToAction("Detail", new { Id = obj.ProjectId });
                }
                return BadRequest();
            }
            // need to add tempdate
            return View();

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddTaskNote(ProjectTaskActivity obj)
        {
            // Manually remove `ProjectTask` from ModelState to prevent validation
            ModelState.Remove("ProjectTask");   
            if (!ModelState.IsValid) // add tempdata
            { 
                // Log or inspect ModelState errors for debugging
                var errors = ModelState.Values.SelectMany(v => v.Errors);
                foreach (var error in errors)
                {
                    Console.WriteLine(error.ErrorMessage);
                }
                return BadRequest(ModelState); 
            }
            bool result = await _projectServ.AddTaskNoteServAsync(obj);
            if (!result) 
            {
                //add tempdata
                return BadRequest();
            }
            return RedirectToAction("Task", new { Id = obj.ProjectTaskId });
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

src/GmphanMvc/Areas/Visitor/Views/Post/Create.cshtml
@model Post 
@{
    ViewData["Title"] = "Create Post";
}
<div class="row justify-content-center">
    <div class="col-lg-10 col-md-12">
        <div class="card mb-3">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h1>Create New Post</h1>
                @* <small>
                    <a asp-area="Visitor" asp-controller="Post"  asp-action="Create" class="btn btn-primary mx-2"> 
                        <i class="bi bi-plus-square"> New Post</i>
                    </a>
                </small> *@
            </div>
            <div class="card-body">
                <form method="post">
                    <div class="p-1 mt-2">
                        <!-- Row for Title with label on the left and input filling the rest of the space -->
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Title" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Title" class="form-control flex-grow-1" placeholder="Post Title" type="text">
                            </div>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Author" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Author" class="form-control flex-grow-1" placeholder="Post Author" type="text">
                            </div>
                            <span asp-validation-for="Author" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="PublishedDate" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="PublishedDate" class="form-control flex-grow-1" placeholder="Published Date" type="date">
                            </div>
                            <span asp-validation-for="PublishedDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Summary" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Summary" class="form-control flex-grow-1" placeholder="Post Summary" type="text">
                            </div>
                            <span asp-validation-for="Summary" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Content" class="me-2" style="min-width: 150px;"></label>
                                <textarea asp-for="Content" class="form-control flex-grow-1" rows="5" placeholder="Content in Markdown format" type="text"></textarea>
                            </div>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                    </div>
                     <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Tags" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Tags" class="form-control flex-grow-1" placeholder="Tags separated by ;" type="text">
                            </div>
                            <span asp-validation-for="Tags" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-3 p-1">
                        <div class="col-md-12 d-flex justify-content-center">
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-secondary form-control">
                                    <i class="bi bi-floppy"></i>  Save
                                </button>
                            </div>
                            @* <div class="col-md-4 ms-2">
                                <a asp-area="Visitor" asp-controller="Project" asp-action="Index" class="btn btn-info form-control">
                                    Back to Project 
                                </a>
                            </div> *@
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div> 

src/GmphanMvc/Areas/Visitor/Views/Post/Edit.cshtml
@{
    @model Post;
}
<div class="row justify-content-center">
    <div class="col-lg-10 col-md-12">
        <div class="card mb-3">
            <h1 class="card-header">Edit Post</h1>
            <form asp-action="Edit" method="post">
                <div class="p-1 mt-2">
                        <!-- Row for Title with label on the left and input filling the rest of the space -->
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Title" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Title" class="form-control flex-grow-1" placeholder="Post Title" type="text">
                            </div>
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Author" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Author" class="form-control flex-grow-1" placeholder="Post Author" type="text">
                            </div>
                            <span asp-validation-for="Author" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="PublishedDate" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="PublishedDate" class="form-control flex-grow-1" placeholder="Published Date" type="date">
                            </div>
                            <span asp-validation-for="PublishedDate" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Summary" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Summary" class="form-control flex-grow-1" placeholder="Post Summary" type="text">
                            </div>
                            <span asp-validation-for="Summary" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Content" class="me-2" style="min-width: 150px;"></label>
                                <textarea asp-for="Content" class="form-control flex-grow-1" rows="5" placeholder="Content in Markdown format" type="text"></textarea>
                            </div>
                            <span asp-validation-for="Content" class="text-danger"></span>
                        </div>
                    </div>
                     <div class="p-1 mt-2">
                        <div class="row mb-1 p-0">
                            <div class="d-flex align-items-center">
                                <label asp-for="Tags" class="me-2" style="min-width: 150px;"></label>
                                <input asp-for="Tags" class="form-control flex-grow-1" placeholder="Tags separated by ;" type="text">
                            </div>
                            <span asp-validation-for="Tags" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-3 p-1">
                        <div class="col-md-12 d-flex justify-content-center">
                            <div class="col-md-2">
                                <button type="submit" class="btn btn-secondary form-control">
                                    <i class="bi bi-floppy"></i>  Save
                                </button>
                            </div>
                            @* <div class="col-md-4 ms-2">
                                <a asp-area="Visitor" asp-controller="Project" asp-action="Index" class="btn btn-info form-control">
                                    Back to Project 
                                </a>
                            </div> *@
                        </div>
                    </div>

            </form>
        </div>
    </div>
</div>

src/GmphanMvc/Areas/Visitor/Views/Post/_Detail.cshtml
@model PostDetailView


<div class="card-body">
  @* <h4 class="card-title">@Model.Title</h4> *@
  <div class="d-flex justify-content-between align-items-center">
      <h6 class="card-subtitle text-muted">By @Model.Author on @Model.PublishedDate.ToShortDateString()</h6>
      <small>
          <a asp-area="Visitor" asp-controller="Post" asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary mx-2"> 
              <i class="bi bi-pencil-square"></i>
          </a>
          @* <a asp-area="Visitor" asp-controller="Post" asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-danger mx-2"> 
              <i class="bi bi-trash3"></i>
          </a> *@
      </small>
  </div>
  <p class="card-text">@Model.Summary</p>
  <div>@Html.Raw(@Model.Content)</div>
</div>

src/GmphanMvc/Areas/Visitor/Views/Post/index.cshtml
@model PostMetaView
@{
    ViewData["Title"] = "Posts";
    var count = 100;
    var index = 0;
    var postMetaData = @Model.PostMetaDTOs;
    var aboutThePostId = 0;
}

<!--Remind to login before doing anything--->

<div class="row justify-content-center">
    <div class="col-lg-10 col-md-12">
        <div class="card mb-3">
            <div class="card-header d-flex justify-content-between align-items-center">
                <h1>Posts </h1>
                <small>
                    <a asp-area="Visitor" asp-controller="Post"  asp-action="Create" class="btn btn-primary mx-2"> 
                        <i class="bi bi-plus-square"> New Post</i>
                    </a>
                </small>
            </div>
            <div class="card-body">
                <div class="accordion" id="accordionExample">
                   
                    @foreach (var item in postMetaData)
                    {
                        var headingId = $"heading{item.Id}";
                        var collapseId = $"collapse{item.Id}";
                        
                        <div class="accordion-item">
                            <h2 class="accordion-header" id="@headingId">
                                <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#@collapseId" aria-expanded="true" aria-controls="@collapseId" onclick="LoadPostDetail(@item.Id)">
                                    @item.Title
                                </button>
                            </h2>

                            <!-- need to show the content if the title is About The Posts -->
                            @if (item.Title == "About The Posts")
                            {
                                aboutThePostId = item.Id;
                                
                                <div id="@collapseId" class="accordion-collapse collapse show" aria-labelledby="@headingId" data-bs-parent="#accordionExample">
                                    <div class="accordion-body" id="accordingBody-@item.Id">
                                        <!---content below will be replace with AJAX responded data
                                        The responded data is the _Detail partial view which combined at return of controller level
                                        -->
                                        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                                    </div>
                                </div>
                                
                            }
                            else
                            {
                                <div id="@collapseId" class="accordion-collapse collapse" aria-labelledby="@headingId" data-bs-parent="#accordionExample">
                                    <div class="accordion-body" id="accordingBody-@item.Id">
                                        <!---content below will be replace with AJAX responded data
                                        The responded data is the _Detail partial view which combined at return of controller level
                                        -->
                                        <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                                    </div>
                                </div>
                            } 
                        </div>
                        
                    }
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts {
    <script>
        function LoadPostDetail(postId) {
            fetch(`/Visitor/Post/GetPostDetail/${postId}`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error("Network response was not ok " + response.statusText);
                    }
                    return response.text();
                })
                .then(data => {
                    // Update the accordion body content with the fetched data/ _Detail partial view
                    document.getElementById(`accordingBody-${postId}`).innerHTML = data;
                })
                .catch(error => {
                    console.error('Error fetching post detail: ', error)
                });
        }
    </script>

    <!-- call the AJAX right away to display About the Posts 
     This is have to be here after the LoadPostDetail function.
    -->
    <script>
        $(document).ready(function() {
            LoadPostDetail(@aboutThePostId);
        });
    </script>
    
}